require('plugins.cmp')
require('plugins.copilot')
require('plugins.copilot_chat')
require('plugins.copilot_cmp')
require('plugins.nvim-tree')
require('plugins.dap')
require('plugins.nvim-treesitter')
require('plugins.nvim-bqf')
require('plugins.telescope')
require('plugins.nvim-autopairs')
require('plugins.neotest')
require('plugins.lualine')
require('plugins.lsp-status')
-- require('plugins.lsp-progress')
